# BUCKET - Users
apiVersion: bucket/v1
kind: Schema
metadata:
  name: users-bucket
spec:
  title: Users
  description: Describe your new bucket
  icon: view_stream
  primary: username
  readOnly: false
  history: false
  properties:
    identity:
      type: string
      title: identity
      description: Description of the identity input
      options:
        position: bottom
    username:
      type: string
      title: username
      description: Description of the username input
      options:
        position: bottom
    thumbnail:
      type: storage
      title: thumbnail
      description: Description of the thumbnail input
      options:
        position: bottom
    email:
      type: string
      title: email
      description: Description of the email input
      options:
        position: bottom
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    surname:
      type: string
      title: surname
      description: Description of the surname input
      options:
        position: bottom
    fcm_token:
      type: string
      title: fcm_token
      description: Description of the fcm_token input
      options:
        position: bottom
    headline:
      type: textarea
      title: headline
      description: Description of the headline input
      options:
        position: bottom
    provider:
      type: string
      title: provider
      description: Description of the provider input
      options:
        position: bottom
      enum:
        - FACEBOOK
        - GOOGLE
        - APPLE
    last_online_date:
      type: date
      title: last_online_date
      description: Description of the last_online_date input
      options:
        position: bottom
      default: :created_at
    language:
      type: string
      title: language
      description: Description of the language input
      options:
        position: bottom
      enum:
        - en
        - tr
        - ru
    notification:
      type: boolean
      title: notification
      description: Description of the notification input
      options:
        position: bottom
      default: true
    timezone:
      type: number
      title: timezone
      description: Description of the timezone input (min)
      options:
        position: bottom
      default: 0
    visibility:
      type: string
      title: visibility
      description: Description of the visibility input
      options:
        position: bottom
      enum:
        - public
        - private
      default: public
    created_at:
      type: date
      title: created_at
      description: Description of the created_at input
      options:
        position: bottom
      readOnly: false
      default: :created_at
    business_account:
      type: boolean
      title: business_account
      description: Description of the business_account input
      options:
        position: bottom
      default: false
    approved:
      type: boolean
      title: approved
      description: Description of the approved input
      options:
        position: bottom
      default: true
  acl:
    write: true==true
    read: true==true
  order: 2
  required:
    - username
---
# BUCKET - Chat Groups
apiVersion: bucket/v1
kind: Schema
metadata:
  name: chat-groups-bucket
spec:
  title: Chat Groups
  description: Describe your new bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: left
    created_at:
      type: date
      title: created_at
      description: Description of the created_at input
      options:
        position: left
      default: :created_at
    last_active:
      type: array
      title: last_active
      description: Description of the last_active input
      options:
        position: right
      items:
        title: Last Active Time
        type: object
        properties:
          date:
            type: date
            title: date
            description: Description of the date input
            options:
              position: bottom
            default: :created_at
          user:
            type: relation
            title: user
            description: Description of the user input
            options:
              position: bottom
            relationType: onetoone
            dependent: false
            bucket:
              resourceFieldRef:
                schemaName: users-bucket
          unread_messages_count:
            type: number
            title: unread_messages_count
            description: Description of the unread_messages_count input
            options:
              position: bottom
            default: 0
          status:
            type: string
            title: status
            description: Description of the status input
            options:
              position: bottom
            enum:
              - active
              - deleted
              - requested
            default: active
    last_message:
      type: string
      title: last_message
      description: Description of the last_message input
      options:
        position: left
    last_message_time:
      type: date
      title: last_message_time
      description: Description of the last_message_time input
      options:
        position: left
    last_message_owner:
      type: relation
      title: last_message_owner
      description: Description of the last_message_owner input
      options:
        position: left
      relationType: onetoone
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: users-bucket
    is_group:
      type: boolean
      title: is_group
      description: Description of the is_group input
      options:
        position: bottom
      default: false
    image:
      type: storage
      title: image
      description: Description of the image input
      options:
        position: bottom
    managers:
      type: relation
      title: managers
      description: Description of the managers input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: users-bucket
  acl:
    write: true==true
    read: true==true
  order: 12
---
# BUCKET - Messages
apiVersion: bucket/v1
kind: Schema
metadata:
  name: messages-bucket
spec:
  title: Messages
  description: Describe your new bucket
  icon: view_stream
  primary: message
  readOnly: false
  history: false
  properties:
    message:
      type: string
      title: message
      description: Description of the message input
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
    owner:
      type: relation
      title: owner
      description: Description of the owner input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: users-bucket
    chat:
      type: relation
      title: chat
      description: Description of the chat input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: chat-groups-bucket
    post:
      type: relation
      title: post
      description: Description of the post input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: text
      bucket:
        resourceFieldRef:
          schemaName: posts-bucket
    image:
      type: storage
      title: image
      description: Description of the image input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 13